<?php

namespace app\validation;

use app\model\subject;

/**
 * 论坛版块删除
 * Class ForumsDel
 * @package app\validation
 */
class ForumsDel extends \pms\Validation
{
    protected function initialize()
    {
        $this->add_exist('id', [
            'message' => 'exist',
            'class_name_list' => subject::class,
            'function_name' => 'findFirstByforum_id',
            'reverse' => true
        ]);
        return parent::initialize(); // TODO: Change the autogenerated stub
    }

}